### ISSUE TITLE
respect longer twoots

### ISSUE THREAD

**Issue by colons** [colons/nkd.su#144]
steps involved:

- stop respecting the old text attribute and work out what we need to handle in this scary new 280-character world
- in a migration, re-query the api for tweets we suspect were truncated (which *should* be easy, given the way they have been truncated)

**Comment by theshillito** [comment]
I appreciate the intention is to move away from twitter, but it's been 2 years and it catches me out a lot as I typically only read comments as I'm announcing the track and then I have to go find the page on-air (which, when combined with clicking avatars expands tracks rather than opens user page/tweet, is kinda awkward).

**Comment by colons** [comment]
okay as of my recent request for https://nkd.su/feed-the-fire/CAE7DF16F3981CFB/, im happy this works now
